services:
  orders-api-container:
    build:
      context: order
    ports:
      - '80:80'


  orders-tests-container:
    build:
      context: test
    volumes:
      - ./test/test_reports:/test/test_reports
    depends_on:
      - orders-api-container
