services:
  orders-api-container:
    build:
      context: ./orders
    ports:
      - '80:80'


  orders-tests-container:
    build:
      context: ./test


  orders-db-container:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=orders_db
    ports:
      - '5432:5432'
    volumes:
      - orders-db-container:/var/lib/postgresql/data


volumes:
  orders-db-container:
    driver: local